### ISSUE TITLE
Deleting Item From Array In Repeat Using Delegate Causes jQuery Error

### ISSUE THREAD

**Issue by sunjay** [aurelia/templating#20]
See the code in this gist:
https://gist.github.com/sunjay/93de4baf2989ff865f47

Starting with the navigation app, I added this to welcome.html:

    <div repeat.for="item of items">
        <button type="button" class="close" aria-label="Close" click.delegate="$parent.deleteItem(item)"><span aria-hidden="true">&times;</span></button>
        ${item}
    </div>

And this to welcome.js:

      constructor(){
        ...
        this.items = [1, 2, 3];
      }
    
      deleteItem(value) {
        const index = this.items.indexOf(value);
        this.items.splice(index, 1);
      }

The problem lies with using `click.delegate`. When the item is deleted, jQuery throws an error.

    Uncaught TypeError: undefined is not a function                         jquery.js:1446
    Sizzle.attr                                                             jquery.js:1642
    Sizzle.selectors.filter.ATTR                                            jquery.js:2143
    i                                                                       jquery.js:2361
    superMatcher                                                            jquery.js:2531
    Sizzle.select                                                           jquery.js:850
    Sizzle                                                                  jquery.js:4475
    jQuery.event.handlers                                                   jquery.js:4412
    jQuery.event.dispatch                                                   jquery.js:4116
    jQuery.event.add.elemData.handle                                        jquery.js:4116

This might have something to do with how the events are being unbinded. You'll notice that the error does not actually occur in any of my added code. It executes afterward.

The error does not occur if I replace .delegate with .trigger

**Comment by sunjay** [comment]
@EisenbergEffect I'm not sure if this issue is a documentation issue or an actual bug. Please take a look.

Thanks

**Comment by zewa666** [comment]
@sunjay I had the same problem when I was working on the Animation support. Will have a closer look at it, but for now just wrap your splice in a setTimeout to avoid the error like this:

```
deleteItem(value) {
    const index = this.items.indexOf(value);
    setTimeout( () => {
      this.items.splice(index, 1);
    },0);
  }
```

**Comment by zewa666** [comment]
Ok seems it has to do something with the event bubbling.

If you do following:

``` html
<div repeat.for="item of items">
    <button type="button" class="close" aria-label="Close" click.delegate="$parent.deleteItem($event, item)"><span aria-hidden="true">&times;</span></button>
    ${item}
</div>
```

```
deleteItem(event, value) {
    event.cancelBubble = true;
    const index = this.items.indexOf(value);
    this.items.splice(index, 1);
  }
```

it will also work.

**Comment by sunjay** [comment]
@zewa666 Thanks. I also mention that at the end of my post. 

> The error does not occur if I replace .delegate with .trigger

**Comment by sunjay** [comment]
Yeah. My guess is that it has something to do with how events are being unbinded. The elements are probably being deleted before the event can be unbinded.

**Comment by sunjay** [comment]
@zewa666 @EisenbergEffect Any update on this? It hasn't been labeled or assigned.

**Comment by zewa666** [comment]
@sunjay honestly I've no clue ... so bumping it up

**Comment by EisenbergEffect** [comment]
@jdanyow @martingust Did we ever discover/fix what was causing this?

**Comment by jdanyow** [comment]
Just took a look at this... used the latest skelly, etc.  Doesn't reproduce in Internet Explorer 11 or Firefox.

In Chrome this error occurs:

![error](http://i.imgur.com/uhEGVdP.png)

If you comment out `import 'bootstrap';` in `app.js` the error goes away (no surprise).

Tried removing `class="close" aria-label="Close"` from the button markup.  This didn't change anything.

**Comment by jdanyow** [comment]
**update...** if you comment out this line of code in `jspm_packages\github\twbs\bootstrap@3.3.4\js\bootstrap.js` the error goes away:

https://github.com/twbs/bootstrap/blob/master/js/alert.js#L92

**Comment by jdanyow** [comment]
I'm stumped... tapping out.

**Comment by The1nternet** [comment]
+1

**Comment by jdanyow** [comment]
@The1nternet  / @sunjay 

I think this will be resolved by https://github.com/aurelia/binding/pull/97

Currently when you use "delegate" it's actually using "trigger" and visa-versa.  https://github.com/aurelia/binding/pull/97 resolves this.

**Comment by EisenbergEffect** [comment]
Should be fixed in the latest.

**Comment by abbasmhd** [comment]
i had the same issue, just comment out  `import 'bootstrap';` in `app.js` the error goes away as per @jdanyow comment

**Comment by andrevlins** [comment]
I'm having this issue today with version 15.3. I'm doing something wrong or the bug still exists in this version?

**Comment by sunjay** [comment]
@andrevlins are you doing the exact same thing or do you have another way of reproducing it?

**Comment by andrevlins** [comment]
@sunjay actually my problem is using `trigger` inside `repeat`, when I use `delegate` the problem goes away.

**Comment by bemon** [comment]
I'm having this issue with version 0.17.5. When using trigger inside repeat & switching to another route.

**Comment by timfish** [comment]
I'm seeing this exact exception in 1.0.0-beta.1 when using `click.trigger` to publish to `EventAggregator` which then removes at item from a `repeat` bound list on the subscribed end. When I use `delegate` I don't see the exception...

**Comment by waywardz** [comment]
We are still see this exception with aurelia-binding@1.0.0-beta.1.1.1 in Chrome 48.0.2564.116.  We are forced to use click.trigger because of the issue the issue with disabled.bind in ie: [https://github.com/aurelia/binding/issues/163](aurelia-binding-163)

**Comment by tolemac** [comment]
Yes, still fail on beta.1.3.1 ...
+1
