### ISSUE TITLE
<compose> element no longer works with dynamic view model

### ISSUE THREAD

**Issue by snortblt** [aurelia/templating#285]
I'm using the <compose> element to host a dynamically selected view at runtime. The bound viewmodel is null initially and is updated asynchronously after the host view loads. This has been working but in the latest (aurelia-framework beta.1.1.4) this has stopped working. this.view is null here in aurelia-templating.js:

`  Controller.prototype.automate = function automate(overrideContext, owningView) {
      this.view.bindingContext = this.viewModel;
      this.view.overrideContext = overrideContext || _aureliaBinding.createOverrideContext(this.viewModel);
      this.view._isUserControlled = true;
...
`

It may be worth noting that the dynamic view model inherits from a base class.

**Comment by EisenbergEffect** [comment]
Can you provide a simple sample that I can use to test things out? If you can create a reproduction on the skeleton and then just attach a zip of the src folder to this ticket, i can track it down and get a fix out.

**Comment by EisenbergEffect** [comment]
Try running `jspm update`. We had a regression composition that was fixed and is now released. Let me know if your problem goes away.

**Comment by snortblt** [comment]
The issue persists after jspm update. It may be difficult to work up an example. I'll see what I can come up with.

**Comment by snortblt** [comment]
[skeleton-typescript-busted-compose.zip](https://github.com/aurelia/templating/files/159280/skeleton-typescript-busted-compose.zip)
Here's a trimmed down version. It doesn't actually produce the same error indicated above, but it does exhibit the issue of never updating the composed view if the bound vm is initially null or undefined. Try uncommenting welcome.ts line 9 to compare.

**Comment by snortblt** [comment]
There may be two issues here. I've further extended the skeleton project to use the view model inheritance as in my real project, where the base view model has @noView applied. With that, I now get the original error at: `this.view.bindingContext = this.viewModel; this.view.overrideContext = overrideContext`
[skeleton-typescript-busted-compose-2.zip](https://github.com/aurelia/templating/files/159318/skeleton-typescript-busted-compose-2.zip)

**Comment by EisenbergEffect** [comment]
Ok, these are two different issues.

The first issue with composition not working has been fixed. I confirmed this. You will need to run `jspm update` to get the latest.

The second issue results from you trying to compose something that has no view. 

That's not supported. However, we could consider it. What exactly would you expect it to do? The code you have in the sample doesn't really make sense.

I'm closing this issue for now since the original issue was fixed. If you want to create a new issue for composing without a view, you can do that, but I'll need a meaningful sample showing what/how you would want that to work.

Thanks!

**Comment by snortblt** [comment]
Thanks, Rob. I may not have explained the second issue clearly. The base class has no view but the derived VMs do. The use case here is being able to switch polymorphic views at runtime. As I mentioned, it all used to work without @noView applied to the base, so maybe this is a red herring now that the first issue is fixed.

**Comment by EisenbergEffect** [comment]
If you remove `noView` from the base class, you should be good to go then.
